// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingSystem.proto

package com.smartparking.grpc;

public interface CarExitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.CarExit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string licensePlate = 1;</code>
   */
  java.lang.String getLicensePlate();
  /**
   * <code>string licensePlate = 1;</code>
   */
  com.google.protobuf.ByteString
      getLicensePlateBytes();

  /**
   * <code>string checkout = 2;</code>
   */
  java.lang.String getCheckout();
  /**
   * <code>string checkout = 2;</code>
   */
  com.google.protobuf.ByteString
      getCheckoutBytes();
}
