// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingSystem.proto

package com.smartparking.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
