// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingSystem.proto

package com.smartparking.grpc;

public interface TicketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.Ticket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string licensePlate = 1;</code>
   */
  java.lang.String getLicensePlate();
  /**
   * <code>string licensePlate = 1;</code>
   */
  com.google.protobuf.ByteString
      getLicensePlateBytes();

  /**
   * <code>string checkin = 2;</code>
   */
  java.lang.String getCheckin();
  /**
   * <code>string checkin = 2;</code>
   */
  com.google.protobuf.ByteString
      getCheckinBytes();

  /**
   * <code>string checkout = 3;</code>
   */
  java.lang.String getCheckout();
  /**
   * <code>string checkout = 3;</code>
   */
  com.google.protobuf.ByteString
      getCheckoutBytes();

  /**
   * <code>string price = 4;</code>
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 4;</code>
   */
  com.google.protobuf.ByteString
      getPriceBytes();
}
