// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FinanceSystem.proto

package com.smartparking.grpc;

public final class FinanceSystemServiceImpl {
  private FinanceSystemServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_Empety_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_Empety_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_Parking_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_Parking_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_FinanceDay_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_FinanceDay_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_Ticket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_Ticket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FinanceSystem.proto\022\rParkingSystem\"\010\n\006" +
      "Empety\"=\n\007Parking\022\030\n\020vancancyQuantity\030\001 " +
      "\001(\t\022\030\n\020openingCashValue\030\002 \001(\t\"1\n\nFinance" +
      "Day\022\023\n\013CarQuantity\030\001 \001(\t\022\016\n\006amount\030\002 \001(\t" +
      "\"P\n\006Ticket\022\024\n\014licensePlate\030\001 \001(\t\022\017\n\007chec" +
      "kin\030\002 \001(\t\022\020\n\010checkout\030\003 \001(\t\022\r\n\005price\030\004 \001" +
      "(\t2\320\002\n\007Finance\0229\n\007payment\022\025.ParkingSyste" +
      "m.Ticket\032\025.ParkingSystem.Ticket\"\000\022G\n\025add" +
      "CarToPaymentRecord\022\025.ParkingSystem.Ticke" +
      "t\032\025.ParkingSystem.Ticket\"\000\022I\n\023PaymentRec" +
      "ordReport\022\025.ParkingSystem.Empety\032\031.Parki" +
      "ngSystem.FinanceDay\"\000\022=\n\007closure\022\025.Parki" +
      "ngSystem.Empety\032\031.ParkingSystem.FinanceD" +
      "ay\"\000\0227\n\004open\022\026.ParkingSystem.Parking\032\025.P" +
      "arkingSystem.Empety\"\000B3\n\025com.smartparkin" +
      "g.grpcB\030FinanceSystemServiceImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ParkingSystem_Empety_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ParkingSystem_Empety_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_Empety_descriptor,
        new java.lang.String[] { });
    internal_static_ParkingSystem_Parking_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ParkingSystem_Parking_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_Parking_descriptor,
        new java.lang.String[] { "VancancyQuantity", "OpeningCashValue", });
    internal_static_ParkingSystem_FinanceDay_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ParkingSystem_FinanceDay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_FinanceDay_descriptor,
        new java.lang.String[] { "CarQuantity", "Amount", });
    internal_static_ParkingSystem_Ticket_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ParkingSystem_Ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_Ticket_descriptor,
        new java.lang.String[] { "LicensePlate", "Checkin", "Checkout", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
