// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FinanceSystem.proto

package com.smartparking.grpc;

public interface ParkingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.Parking)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vancancyQuantity = 1;</code>
   */
  java.lang.String getVancancyQuantity();
  /**
   * <code>string vancancyQuantity = 1;</code>
   */
  com.google.protobuf.ByteString
      getVancancyQuantityBytes();

  /**
   * <code>string openingCashValue = 2;</code>
   */
  java.lang.String getOpeningCashValue();
  /**
   * <code>string openingCashValue = 2;</code>
   */
  com.google.protobuf.ByteString
      getOpeningCashValueBytes();
}
