// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingSystem.proto

package com.smartparking.grpc;

public interface FinanceDayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.FinanceDay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string CarQuantity = 1;</code>
   */
  java.lang.String getCarQuantity();
  /**
   * <code>string CarQuantity = 1;</code>
   */
  com.google.protobuf.ByteString
      getCarQuantityBytes();

  /**
   * <code>string amount = 2;</code>
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 2;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();
}
