// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingSystem.proto

package com.smartparking.grpc;

/**
 * Protobuf type {@code ParkingSystem.CarExit}
 */
public  final class CarExit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ParkingSystem.CarExit)
    CarExitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CarExit.newBuilder() to construct.
  private CarExit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CarExit() {
    licensePlate_ = "";
    checkout_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CarExit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            licensePlate_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            checkout_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartparking.grpc.ParkingSystemServiceImpl.internal_static_ParkingSystem_CarExit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartparking.grpc.ParkingSystemServiceImpl.internal_static_ParkingSystem_CarExit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartparking.grpc.CarExit.class, com.smartparking.grpc.CarExit.Builder.class);
  }

  public static final int LICENSEPLATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object licensePlate_;
  /**
   * <code>string licensePlate = 1;</code>
   */
  public java.lang.String getLicensePlate() {
    java.lang.Object ref = licensePlate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      licensePlate_ = s;
      return s;
    }
  }
  /**
   * <code>string licensePlate = 1;</code>
   */
  public com.google.protobuf.ByteString
      getLicensePlateBytes() {
    java.lang.Object ref = licensePlate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      licensePlate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECKOUT_FIELD_NUMBER = 2;
  private volatile java.lang.Object checkout_;
  /**
   * <code>string checkout = 2;</code>
   */
  public java.lang.String getCheckout() {
    java.lang.Object ref = checkout_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checkout_ = s;
      return s;
    }
  }
  /**
   * <code>string checkout = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCheckoutBytes() {
    java.lang.Object ref = checkout_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checkout_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLicensePlateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, licensePlate_);
    }
    if (!getCheckoutBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, checkout_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLicensePlateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, licensePlate_);
    }
    if (!getCheckoutBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, checkout_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartparking.grpc.CarExit)) {
      return super.equals(obj);
    }
    com.smartparking.grpc.CarExit other = (com.smartparking.grpc.CarExit) obj;

    boolean result = true;
    result = result && getLicensePlate()
        .equals(other.getLicensePlate());
    result = result && getCheckout()
        .equals(other.getCheckout());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LICENSEPLATE_FIELD_NUMBER;
    hash = (53 * hash) + getLicensePlate().hashCode();
    hash = (37 * hash) + CHECKOUT_FIELD_NUMBER;
    hash = (53 * hash) + getCheckout().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartparking.grpc.CarExit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartparking.grpc.CarExit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartparking.grpc.CarExit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartparking.grpc.CarExit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartparking.grpc.CarExit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartparking.grpc.CarExit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartparking.grpc.CarExit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartparking.grpc.CarExit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartparking.grpc.CarExit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartparking.grpc.CarExit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartparking.grpc.CarExit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartparking.grpc.CarExit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartparking.grpc.CarExit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ParkingSystem.CarExit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ParkingSystem.CarExit)
      com.smartparking.grpc.CarExitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartparking.grpc.ParkingSystemServiceImpl.internal_static_ParkingSystem_CarExit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartparking.grpc.ParkingSystemServiceImpl.internal_static_ParkingSystem_CarExit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartparking.grpc.CarExit.class, com.smartparking.grpc.CarExit.Builder.class);
    }

    // Construct using com.smartparking.grpc.CarExit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      licensePlate_ = "";

      checkout_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartparking.grpc.ParkingSystemServiceImpl.internal_static_ParkingSystem_CarExit_descriptor;
    }

    @java.lang.Override
    public com.smartparking.grpc.CarExit getDefaultInstanceForType() {
      return com.smartparking.grpc.CarExit.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartparking.grpc.CarExit build() {
      com.smartparking.grpc.CarExit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartparking.grpc.CarExit buildPartial() {
      com.smartparking.grpc.CarExit result = new com.smartparking.grpc.CarExit(this);
      result.licensePlate_ = licensePlate_;
      result.checkout_ = checkout_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartparking.grpc.CarExit) {
        return mergeFrom((com.smartparking.grpc.CarExit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartparking.grpc.CarExit other) {
      if (other == com.smartparking.grpc.CarExit.getDefaultInstance()) return this;
      if (!other.getLicensePlate().isEmpty()) {
        licensePlate_ = other.licensePlate_;
        onChanged();
      }
      if (!other.getCheckout().isEmpty()) {
        checkout_ = other.checkout_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartparking.grpc.CarExit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartparking.grpc.CarExit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object licensePlate_ = "";
    /**
     * <code>string licensePlate = 1;</code>
     */
    public java.lang.String getLicensePlate() {
      java.lang.Object ref = licensePlate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        licensePlate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string licensePlate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLicensePlateBytes() {
      java.lang.Object ref = licensePlate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        licensePlate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string licensePlate = 1;</code>
     */
    public Builder setLicensePlate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      licensePlate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string licensePlate = 1;</code>
     */
    public Builder clearLicensePlate() {
      
      licensePlate_ = getDefaultInstance().getLicensePlate();
      onChanged();
      return this;
    }
    /**
     * <code>string licensePlate = 1;</code>
     */
    public Builder setLicensePlateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      licensePlate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object checkout_ = "";
    /**
     * <code>string checkout = 2;</code>
     */
    public java.lang.String getCheckout() {
      java.lang.Object ref = checkout_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checkout_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string checkout = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCheckoutBytes() {
      java.lang.Object ref = checkout_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checkout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string checkout = 2;</code>
     */
    public Builder setCheckout(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      checkout_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string checkout = 2;</code>
     */
    public Builder clearCheckout() {
      
      checkout_ = getDefaultInstance().getCheckout();
      onChanged();
      return this;
    }
    /**
     * <code>string checkout = 2;</code>
     */
    public Builder setCheckoutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      checkout_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ParkingSystem.CarExit)
  }

  // @@protoc_insertion_point(class_scope:ParkingSystem.CarExit)
  private static final com.smartparking.grpc.CarExit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartparking.grpc.CarExit();
  }

  public static com.smartparking.grpc.CarExit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CarExit>
      PARSER = new com.google.protobuf.AbstractParser<CarExit>() {
    @java.lang.Override
    public CarExit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CarExit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CarExit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CarExit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartparking.grpc.CarExit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

