// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingSystem.proto

package com.smartparking.grpc;

public interface CarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.Car)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string color = 1;</code>
   */
  java.lang.String getColor();
  /**
   * <code>string color = 1;</code>
   */
  com.google.protobuf.ByteString
      getColorBytes();

  /**
   * <code>string licensePlate = 2;</code>
   */
  java.lang.String getLicensePlate();
  /**
   * <code>string licensePlate = 2;</code>
   */
  com.google.protobuf.ByteString
      getLicensePlateBytes();

  /**
   * <code>string checkin = 3;</code>
   */
  java.lang.String getCheckin();
  /**
   * <code>string checkin = 3;</code>
   */
  com.google.protobuf.ByteString
      getCheckinBytes();

  /**
   * <code>string checkout = 4;</code>
   */
  java.lang.String getCheckout();
  /**
   * <code>string checkout = 4;</code>
   */
  com.google.protobuf.ByteString
      getCheckoutBytes();
}
