// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingSystem.proto

package com.smartparking.grpc;

public interface EmpetyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.Empety)
    com.google.protobuf.MessageOrBuilder {
}
