// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParkingSystem.proto

package com.smartparking.grpc;

public final class ParkingSystemServiceImpl {
  private ParkingSystemServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_Car_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_Car_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_Ticket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_Ticket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ParkingSystem.proto\022\rParkingSystem\"M\n\003" +
      "Car\022\r\n\005color\030\001 \001(\t\022\024\n\014licensePlate\030\002 \001(\t" +
      "\022\017\n\007checkin\030\003 \001(\t\022\020\n\010checkout\030\004 \001(\t\"_\n\006T" +
      "icket\022\r\n\005color\030\001 \001(\t\022\024\n\014licensePlate\030\002 \001" +
      "(\t\022\017\n\007checkin\030\003 \001(\t\022\020\n\010checkout\030\004 \001(\t\022\r\n" +
      "\005price\030\005 \001(\t2\207\001\n\016ParkingManaged\0229\n\ncarCh" +
      "eckIn\022\022.ParkingSystem.Car\032\025.ParkingSyste" +
      "m.Ticket\"\000\022:\n\013CarCheckOut\022\022.ParkingSyste" +
      "m.Car\032\025.ParkingSystem.Ticket\"\000B3\n\025com.sm" +
      "artparking.grpcB\030ParkingSystemServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ParkingSystem_Car_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ParkingSystem_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_Car_descriptor,
        new java.lang.String[] { "Color", "LicensePlate", "Checkin", "Checkout", });
    internal_static_ParkingSystem_Ticket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ParkingSystem_Ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_Ticket_descriptor,
        new java.lang.String[] { "Color", "LicensePlate", "Checkin", "Checkout", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
