// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VancancyManagement.proto

package com.smartparking.grpc;

public interface CarEntranceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.CarEntrance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string licensePlate = 1;</code>
   */
  java.lang.String getLicensePlate();
  /**
   * <code>string licensePlate = 1;</code>
   */
  com.google.protobuf.ByteString
      getLicensePlateBytes();
}
