// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VancancyManagement.proto

package com.smartparking.grpc;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.empty)
    com.google.protobuf.MessageOrBuilder {
}
