// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VancancyManagement.proto

package com.smartparking.grpc;

public interface TicketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.Ticket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idTicket = 1;</code>
   */
  java.lang.String getIdTicket();
  /**
   * <code>string idTicket = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdTicketBytes();

  /**
   * <code>string licensePlate = 2;</code>
   */
  java.lang.String getLicensePlate();
  /**
   * <code>string licensePlate = 2;</code>
   */
  com.google.protobuf.ByteString
      getLicensePlateBytes();

  /**
   * <code>string checkin = 3;</code>
   */
  java.lang.String getCheckin();
  /**
   * <code>string checkin = 3;</code>
   */
  com.google.protobuf.ByteString
      getCheckinBytes();

  /**
   * <code>string checkout = 4;</code>
   */
  java.lang.String getCheckout();
  /**
   * <code>string checkout = 4;</code>
   */
  com.google.protobuf.ByteString
      getCheckoutBytes();

  /**
   * <code>double price = 5;</code>
   */
  double getPrice();
}
