// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VancancyManagement.proto

package com.smartparking.grpc;

public interface TicketRequestCheckoutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParkingSystem.TicketRequestCheckout)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string idTicket = 1;</code>
   */
  java.lang.String getIdTicket();
  /**
   * <code>string idTicket = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdTicketBytes();
}
