// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VancancyManagement.proto

package com.smartparking.grpc;

public final class VancancyManagementServiceImpl {
  private VancancyManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_Ticket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_Ticket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParkingSystem_CarEntrance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParkingSystem_CarEntrance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030VancancyManagement.proto\022\rParkingSyste" +
      "m\032\036google/protobuf/duration.proto\032\037googl" +
      "e/protobuf/timestamp.proto\"b\n\006Ticket\022\020\n\010" +
      "idTicket\030\001 \001(\t\022\024\n\014licensePlate\030\002 \001(\t\022\017\n\007" +
      "checkin\030\003 \001(\t\022\020\n\010checkout\030\004 \001(\t\022\r\n\005price" +
      "\030\005 \001(\001\"\030\n\006Status\022\016\n\006status\030\001 \001(\t\"#\n\013CarE" +
      "ntrance\022\024\n\014licensePlate\030\001 \001(\t2\353\001\n\022Vancan" +
      "cyManagement\022F\n\017vancancyCheckIn\022\032.Parkin" +
      "gSystem.CarEntrance\032\025.ParkingSystem.Tick" +
      "et\"\000\022B\n\020vancancyCheckOut\022\025.ParkingSystem" +
      ".Ticket\032\025.ParkingSystem.Ticket\"\000\022I\n\027vanc" +
      "ancyCheckIfItIsFull\022\025.ParkingSystem.Stat" +
      "us\032\025.ParkingSystem.Ticket\"\000B8\n\025com.smart" +
      "parking.grpcB\035VancancyManagementServiceI" +
      "mplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_ParkingSystem_Ticket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ParkingSystem_Ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_Ticket_descriptor,
        new java.lang.String[] { "IdTicket", "LicensePlate", "Checkin", "Checkout", "Price", });
    internal_static_ParkingSystem_Status_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ParkingSystem_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_Status_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_ParkingSystem_CarEntrance_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ParkingSystem_CarEntrance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParkingSystem_CarEntrance_descriptor,
        new java.lang.String[] { "LicensePlate", });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
